export const movies = [
  {
    Title: 'Once Upon a Time... in Hollywood',
    Year: '2019',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg',
    Plot: "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
    imdbRating: '7.7',
    id: 'tt7131622',
    isMyMovie: true,
  },
  {
    Title: 'The Hateful Eight',
    Year: '2015',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg',
    Plot: "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
    imdbRating: '7.8',
    id: 'tt3460252',
    isMyMovie: false,
  },
  {
    Title: 'Django Unchained',
    Year: '2012',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg',
    Plot: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    imdbRating: '8.4',
    id: 'tt1853728',
    isMyMovie: false,
  },
  {
    Title: 'Kill Bill: The Whole Bloody Affair',
    Year: '2011',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYmFkNTc1MWYtYTVlNy00NmZmLTkzMjAtMWM0N2FmMWRkNWNhXkEyXkFqcGdeQXVyMTE5NDkxMA@@._V1_SX300.jpg',
    Plot: "The Bride must kill her ex-boss and lover Bill who betrayed her at her wedding rehearsal, shot her in the head and took away her unborn daughter. But first, she must make the other four members of the Deadly Viper Assassination Squad suffer.",
    imdbRating: '8.8',
    id: 'tt6019206',
    isMyMovie: false,
  },
  {
    Title: 'Inglourious Basterds',
    Year: '2009',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg',
    Plot: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
    imdbRating: '8.3',
    id: 'tt0361748',
    isMyMovie: false,
  },
  {
    Title: 'Death Proof',
    Year: '2007',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYTdmZmY3Y2QtNjU5NC00OGUxLTg3MWQtMmE2ODM5Mzg3MzcyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Plot: "Two separate sets of voluptuous women are stalked at different times by a scarred stuntman who uses his \"death proof\" cars to execute his murderous plans.",
    imdbRating: '7.0',
    id: 'tt1028528',
    isMyMovie: false,
  },
  {
    Title: 'Kill Bill: Vol. 2',
    Year: '2004',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNmFiYmJmN2QtNWQwMi00MzliLThiOWMtZjQxNGRhZTQ1MjgyXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg',
    Plot: "The Bride continues her quest of vengeance against her former boss and lover Bill, the reclusive bouncer Budd, and the treacherous, one-eyed Elle.",
    imdbRating: '8.0',
    id: 'tt0378194',
    isMyMovie: false,
  },
  {
    Title: 'Kill Bill: Vol. 1',
    Year: '2003',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Plot: "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.",
    imdbRating: '8.1',
    id: 'tt0266697',
    isMyMovie: false,
  },
];
